### ISSUE TITLE
No module named 'progressbar'

### ISSUE THREAD

**Issue by ghshin-github** [CCS-Lab/easyml#106]
I got an error message "No module named 'progressbar'". I checked that, after installing the package through pip, the file 'progressbar.py' does not exist under the 'easymlpy' folder. I guess that the file is missing from the outset and 'progressbar' is still called when core.py runs, which produces this error. Could you check this?

**Comment by paulhendricks** [comment]
Can you try this?

```
pip install progressbar2
```

https://pypi.org/project/progressbar2/

And see here: https://github.com/CCS-Lab/easyml/tree/master/Python#installation

**Comment by ghshin-github** [comment]
Thanks for the reply. I did what you said, but I keep seeing an error message (which is different from the previous one). I think this is a problem of my computer. I will troubleshoot it on my own. Thank you again.
