### ISSUE TITLE
Make it optional to save beta weights and ROC curves? / How to name files? / set or display paths for saving files

### ISSUE THREAD

**Issue by youngahn** [CCS-Lab/easyml#33]
1. Currently beta weights and ROC curves are saved in the current working directory by default. Would it be a better idea to make it optional (default=T)? 

2. File names are the same for any datasets (e.g., betas.png; train_roc_curve.png...). It is possible that files will be overwritten by mistake. 

3. Display the current working directory in the R console so that users can easily find the files?

**Comment by paulhendricks** [comment]
Solved by 5cfb77fe37d440547229b3bde82bbb1eba580cfe. Each `easy_*` call will return a results object that allows users to save the beta weights, predictions, metrics, and associated plots, however they prefer.

**Comment by paulhendricks** [comment]
Closed too quickly; need to implement in Python!

**Comment by paulhendricks** [comment]
Finished in Python! All results are objects that can be saved however needed!
