### ISSUE TITLE
Machine learning analysis of fMRI data

### ISSUE THREAD

**Issue by youngahn** [CCS-Lab/easyml#54]
Program some Python codes:

1. Read paths to first-level fMRI data (inputs: paths to 1st level data) 
2. Convert all subjects' fMRI data (in MNI space) into a ML-ready matrix (inputs: 1st level paths & a mask file).
3. After ML analysis, reshape ML-ready matrix into the MNI space. 

One should be able to perform each step with a single line of code.

**Comment by paulhendricks** [comment]
Very good idea.

Let's talk about putting this in a separate package, perhaps `easyfmri`?
