### ISSUE TITLE
Error in easy_glmnet

### ISSUE THREAD

**Issue by youngahn** [CCS-Lab/easyml#57]
```
data("cocaine_dependence", package = "easyml")
easy_glmnet(cocaine_dependence, "diagnosis", 
                      family = "binomial", exclude_variables = c("subject", "age"), 
                      categorical_variables = c("male"))
```
[1] "Replicating coefficients:"
  |==================================================| 100% elapsed =03s, remaining ~00s
Error in easy_glmnet(cocaine_dependence, "diagnosis", family = "binomial",  : 
  could not find function "plot_coefficients_processed"

**Comment by paulhendricks** [comment]
See 9f29e6ce8d9a71f816b79fb969f1edbcf55ea81e.
