### ISSUE TITLE
Random forest on a continuous dependent measure --> replace RMSE with correlation coefficients

### ISSUE THREAD

**Issue by youngahn** [CCS-Lab/easyml#75]
With easy_random_forest, currently I see histograms of RMSE across X number of training/test divisions. Just like easy_glmnet, it should plot histograms of correlation coefficients (perhaps along with RMSE?).

**Comment by Nathaniel-Haines** [comment]
The easy_random_forest() function will output histograms of R^2 metrics if the `measure` argument is set to `measure_r2_score` (i.e. `measure = measure_r2_score`). If this is made the default, I think it would solve the issue.

**Comment by paulhendricks** [comment]
See e94013dc8bee9a8f8189b14669ba8713555c4646.
